CREATE TABLE `Labels` (
    `id` CHAR(36) NOT NULL,
    `user_id` CHAR(36) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    `name` CHAR(50) NOT NULL,
    `color` CHAR(7) DEFAULT '#ffffff',
    `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `id` (`id`),
    KEY `user_id` (`user_id`),
    CONSTRAINT `Labels_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;